style: gitlab
template: CHANGELOG.tpl.md
info:
  title: 🕔 变更记录
  repository_url: https://github.com/godoes/gorm-oracle
options:
  tag_filter_pattern: '^v'
  sort: "date"
  commits:
    filters:
      Type:
        - 🎉
        - ✨
        - 🚩
        - 🔖
        - 🩹
        - 🐛
        - 🚑️
        - 🔒️
        - 🔐
        - 🚨
        - ♻️
        - 👔
        - 🍱
        - 🔨
        - 🔧
        - 🙈
        - 💡
        - 📝
        - ⬆️
        - ⬇️
        - 🚚
        - 🏗️
        - 👽️
        - 💥
        - ⚡️
        - 🚸
        - 🔊
        - 🔇
        - 💄
        - 🎨
        - 🧱
        - 👷
        - 💚
        - 🚀
        - 🧵
        - 🛂
        - 🦺
        - 🔥
        - 🏁
        - 🐧
        - 🗃️
        - 👥
        - 📄
        - 🌐
        - ✅
        - 🧪
        - "Merge"
  commit_groups:
    sort_by: RawTitle
    title_maps:
      🎉: 初始化
      ✨: 新特性
      🚩: 功能标识
      🔖: 版本发布
      🩹: 修改优化
      🐛: 问题修复
      🚑️: 紧急修复
      🔒️: 安全修复
      🔐: 加密相关
      🚨: 修复警告
      ♻️: 代码重构
      👔: 业务逻辑
      🍱: 资源文件
      🔨: 开发配置
      🔧: 程序配置
      🙈: 忽略配置
      💡: 注释文档
      📝: 说明文档
      ⬆️: 依赖升级
      ⬇️: 依赖降级
      🚚: 移动文件
      🏗️: 架构变更
      👽️: 外部变更
      💥: 突破变更
      ⚡️: 性能优化
      🚸: 用户体验
      🔊: 更新日志
      🔇: 移除日志
      💄: 界面样式
      🎨: 代码格式
      🧱: 基础设施
      👷: 持续集成
      💚: 修复构建
      🚀: 部署
      🧵: 并发
      🛂: 权限
      🦺: 验证
      🔥: 删除
      🏁: Windows
      🐧: Unix
      🗃️: 数据库
      👥: 贡献者
      📄: 许可证
      🌐: 国际化
      ✅: 通过的测试
      🧪: 失败的测试
      "Merge": 合并
  header:
    # pattern: "^(.*)$"
    # https://regex101.com/r/wEipOM/1
    # https://emojipedia.org/emoji/%E2%9C%A8/
    pattern: "^(Merge|[\\x{1F300}-\\x{1F5FF}\\x{1F600}-\\x{1F64F}\\x{1F680}-\\x{1F6FF}\\x{1F700}-\\x{1F77F}\\x{1F780}-\\x{1F7FF}\\x{1F800}-\\x{1F8FF}\\x{1F900}-\\x{1F9FF}\\x{1FA00}-\\x{1FA6F}\\x{1FA70}-\\x{1FAFF}\\x{2600}-\\x{26FF}\\x{2700}-\\x{27BF}]|[\\x{2B05}\\x{2B06}\\x{2B07}\\x{23EA}\\x{23EB}])(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - 💥
